spec:
  inputs:
    php_version:
      default: $DP_PHP_VERSION
    joomla_version:
      default: $DP_JOOMLA_VERSION
---

include:
  - project: 'Digital-Peak/DPCIComponents'
    file: '/templates/Digital-Peak-Joomla-Extension.yml'
    inputs:
      php_version: $[[ inputs.php_version ]]
      joomla_version: $[[ inputs.joomla_version ]]
